apiVersion: v1
kind: Service
metadata:
  name: netflix-services
  namespace: subbu-1-ns
spec:
  type: LoadBalancer # Use ClusterIP or NodePort based on your requirements
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: netflix